# -*- coding: utf-8 -*-
"""yolov4_tooth_micrography.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EdhwarRUGL7eDh76I3cZvFhhMwwzL6MX
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd ..
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/ /mydrive

# Commented out IPython magic to ensure Python compatibility.
# %cd /mydrive/yolov4

!git clone https://github.com/AlexeyAB/darknet

# Commented out IPython magic to ensure Python compatibility.
# %cd darknet/
!sed -i 's/OPENCV=0/OPENCV=1/' Makefile
!sed -i 's/GPU=0/GPU=1/' Makefile
!sed -i 's/CUDNN=0/CUDNN=1/' Makefile
!sed -i 's/CUDNN_HALF=0/CUDNN_HALF=1/' Makefile
!sed -i 's/LIBSO=0/LIBSO=1/' Makefile

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd data/
!find -maxdepth 1 -type f -exec rm -rf {} \;
# %cd ..
# %rm -rf cfg/
# %mkdir cfg

!unzip /mydrive/yolov4/obj.zip -d data/

!cp /mydrive/yolov4/yolov4-custom.cfg cfg

!cp /mydrive/yolov4/obj.names data
!cp /mydrive/yolov4/obj.data  data

!cp /mydrive/yolov4/process.py .

!python process.py

!ls data/

!wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.conv.137

!./darknet detector train data/obj.data cfg/yolov4-custom.cfg yolov4.conv.137 -dont_show -map

!./darknet detector train data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_last.weights -dont_show -map

# Commented out IPython magic to ensure Python compatibility.

def imShow(path):

  import cv2
  import matplotlib.pyplot as plt
#   %matplotlib inline
  image = cv2.imread(path)
  height, width = image.shape[:2]
  resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)
  fig = plt.gcf()
  fig.set_size_inches(18, 10)
  plt.axis("off")
  plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
  plt.show()

import matplotlib.pyplot as plt
imgplot = plt.imshow('chart.png')

!./darknet detector map data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_1000.weights -points 0

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights /content/gdrive/MyDrive/yolov4/data/obj/101_0_102.jpg -thresh 0.3
imShow('predictions.jpg')

image = cv2.imread(content/gdrive/MyDrive/ml_3d_tooth/camera_micrography/1.jpg)
plt(image)

# Commented out IPython magic to ensure Python compatibility.
# %cd cfg
!sed -i 's/batch=64/batch=1/' yolov4-custom.cfg
!sed -i 's/subdivisions=16/subdivisions=1/' yolov4-custom.cfg
# %cd ..

import os, sys 
Pixel_3_dirs = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/')
Iphone_6_dirs = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/')
S_A12 = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/')
S_A31 = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/')
S_S10 = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/')
S_S10_5G = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/')
S_S10e = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/')
S_S20 = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/')

Pixel_3_dirs

import matplotlib.pyplot as plt
import numpy as np

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/1. Root Caries 1st Molar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 1)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/2. Pulp Necrosis 2nd Molar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 2)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/3. Secondary caries 2nd Premolar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 3)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/4. Pulp Necrosis 3rd Molar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 4)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/5. Pulp Necrosis lower 1st molar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 5)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/6. root caries 2nd Molar, Pixel 3.png' -thresh 0.3
plt.subplot(1, 6, 6)
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/1. Root Caries 1st Molar, Pixel 3.png' -thresh 0.3

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 1.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 2.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 3.png' -thresh 0.3
imShow('predictions.jpg')


!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 4.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 5.png' -thresh 0.3
imShow('predictions.jpg')

!./darknet detector test data/obj.data cfg/yolov4-custom.cfg /mydrive/yolov4/training/yolov4-custom_best.weights '/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 6.png' -thresh 0.3
imShow('predictions.jpg')

def mse(imageA, imageB):
  imgA = np.asarray(imageA)
  imgB = np.asarray(imageB)

  err = np.sum((imgA - imgB)**2) / float(imgA.shape[0] * imgA.shape[1])
  return err

import numpy as np
import cv2
from PIL import Image
import os
import PIL
import glob
import sys 
from skimage.metrics import structural_similarity as ssim

def ssim_n(imageA, imageB):
  imgA = np.asarray(imageA)
  imgB = np.asarray(imageB)

  return ssim(imgA, imgB, data_range=imgB.max() - imgB.min())

#for image 1

print(mse(cv2.imread('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/1. Root Caries 1st Molar, Pixel 3.png'), cv2.imread('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 1.png')))

folders = os.listdir('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/')
print(folders)

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/1. Root Caries 1st Molar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 1.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 1.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 1.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 1.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 1.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 1.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 1.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_1 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_1)
#print(ssim_n(pixel_fig1, pixel_fig1), ssim_n(pixel_fig1, iphone_6s_fig1), ssim_n(pixel_fig1, S_A12), ssim_n(pixel_fig1, S_A31), ssim_n(pixel_fig1, S_S10), ssim_n(pixel_fig1, S_S10_5g), ssim_n(pixel_fig1, S_S10e), ssim_n(pixel_fig1, S_S20))

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/2. Pulp Necrosis 2nd Molar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 2.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 2.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 2.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 2.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 2.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 2.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 2.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_2 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_2)

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/3. Secondary caries 2nd Premolar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 3.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 3.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 3.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 3.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 3.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 3.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 3.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_3 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_3)

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/4. Pulp Necrosis 3rd Molar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 4.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 4.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 4.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 4.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 4.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 4.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 4.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_4 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_4)

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/5. Pulp Necrosis lower 1st molar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 5.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 5.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 5.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 5.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 5.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 5.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 5.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_5 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_5)

pixel_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Google Pixel 3/6. root caries 2nd Molar, Pixel 3.png')
size = pixel_fig1.size
iphone_6s_fig1 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Iphone 6s/Figure 6.png')
iphone_6s_fig1 = iphone_6s_fig1.resize((size[0],size[1]))

S_A12 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A12/Figure 6.png')
S_A12 = S_A12.resize((size[0],size[1]))

S_A31 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung A31/Figure 6.png')
S_A31 = S_A31.resize((size[0],size[1]))

S_S10 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10/Figure 6.png')
S_S10 = S_S10.resize((size[0],size[1]))

S_S10_5g = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10 5G/Figure 6.png')
S_S10_5g = S_S10_5g.resize((size[0],size[1]))

S_S10e = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S10e/Figure 6.png')
S_S10e = S_S10e.resize((size[0],size[1]))

S_S20 = Image.open('/content/gdrive/MyDrive/ml_3d_tooth/Processed images/Samsung S20/Figure 6.png')
S_S20 = S_S20.resize((size[0],size[1]))

figure_6 =[mse(pixel_fig1, pixel_fig1), mse(pixel_fig1, iphone_6s_fig1), mse(pixel_fig1, S_A12), mse(pixel_fig1, S_A31), mse(pixel_fig1, S_S10), mse(pixel_fig1, S_S10_5g), mse(pixel_fig1, S_S10e), mse(pixel_fig1, S_S20)]
print(figure_6)

figure_1.hist()

import pandas as pd

df = pd.DataFrame(figure_1, figure_2, figure_3, figure_4, figure_5, figure_6, index =['Pixel3', 'Iphone6s', 'SamsungA12', 'SamsungA31', 'SamsungS10', 'SamsungS10 5G', 'SamsungS10e', 'SamsungS20'],
                                              columns =folders)

!./darknet detector map data/obj.data cfg/yolov4-custom.cfg /content/gdrive/MyDrive/yolov4/training/yolov4-custom_best.weights -points 0

